#!/usr/bin/env python3
"""
tools/update_outline.py
Automatically regenerates outline.md by inspecting the active project structure,
discovering layouts, settings screens, key classes, and packages.
"""

import os
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
OUTLINE_FILE = REPO_ROOT / "outline.md"
APP_DIR = REPO_ROOT / "app" / "src" / "main"


def list_layouts():
    layout_main_dir = APP_DIR / "assets" / "layouts" / "main"
    if not layout_main_dir.exists():
        return []
    layouts = sorted([f.stem for f in layout_main_dir.glob("*.json")])
    return layouts


def list_settings_screens():
    screens_dir = APP_DIR / "java" / "helium314" / "keyboard" / "settings" / "screens"
    if not screens_dir.exists():
        return []
    screens = sorted([f.name for f in screens_dir.glob("*Screen.kt")])
    return screens


def list_layout_categories():
    layouts_dir = APP_DIR / "assets" / "layouts"
    if not layouts_dir.exists():
        return []
    categories = sorted([d.name for d in layouts_dir.iterdir() if d.is_dir()])
    return categories


def generate_outline_content():
    layouts = list_layouts()
    screens = list_settings_screens()
    layout_categories = list_layout_categories()

    layout_items_str = ", ".join(f"`{l}`" for l in layouts)
    screen_items_str = ", ".join(f"`{s}`" for s in screens)
    categories_str = ", ".join(f"`{c}`" for c in layout_categories)

    content = f"""# LeanType (HeliboardL) Architectural Codebase Outline

> [!NOTE]
> This outline is auto-generated by `tools/update_outline.py` to reflect the active codebase architecture.
> Consult this outline first before performing code searches or modifications to identify exact modules, entry points, and classes.

---

## 1. System Architecture Overview

LeanType is a privacy-focused, highly customizable Android Input Method Editor (IME) based on the AOSP LatinIME engine and HeliBoard, extended with modern Jetpack Compose settings, customizable layouts (FlorisBoard format), offline/online AI voice input, and high-performance NDK components.

### Core Stack
* **Language**: Kotlin (primary), Java (legacy AOSP bridges), C++ (NDK dictionary trie and spatial proximity).
* **UI**: Android Custom Canvas Views (`KeyboardView`, `MainKeyboardView`) for high-speed 60fps IME rendering; Jetpack Compose for Settings activities and dialogs.
* **Build Flavors**:
  * `standard`: Full feature set including network AI/voice services (Groq Whisper, AI rewrite).
  * `offline`: Completely air-gapped; zero internet permissions.

---

## 2. Directory Structure Tree

```
HeliboardL/
├── app/
│   ├── src/main/
│   │   ├── aidl/                     # IPC interfaces for external voice/AI services
│   │   ├── assets/                   # Layouts, dictionaries, emoji databases
│   │   │   ├── dicts/                # Built-in binary dictionary packs (.dict)
│   │   │   ├── emoji/                # Emoji definitions and category mappings
│   │   │   ├── layouts/              # FlorisBoard-compatible JSON layout definitions
│   │   │   │   ├── main/             # Main alphabet layouts ({len(layouts)} layouts available)
│   │   │   │   ├── functional/       # Shift, delete, enter, spacebar configurations
│   │   │   │   ├── number_row/       # Top row number overlays
│   │   │   │   ├── symbols/          # Symbol screen definitions
│   │   │   │   └── ...               # Categories: {categories_str}
│   │   ├── java/
│   │   │   ├── com/android/inputmethod/  # AOSP legacy proximity & dictionary interfaces
│   │   │   ├── com/leanbitlab/leantype/  # LeanType voice service & Groq integrations
│   │   │   └── helium314/keyboard/       # Core application package
│   │   │       ├── accessibility/        # Spoken descriptions & accessibility services
│   │   │       ├── compat/               # Android OS backward compatibility shims
│   │   │       ├── dictionarypack/       # External dictionary pack downloads/handlers
│   │   │       ├── event/                # Key events, combiners (Dead keys, Hangul)
│   │   │       ├── keyboard/             # Views, Canvas rendering, touch tracking
│   │   │       │   ├── clipboard/        # Clipboard history UI & pin manager
│   │   │       │   ├── emoji/            # Emoji picker, tabs, skin tone popups
│   │   │       │   └── internal/         # KeyboardBuilder, geometry & layout parsers
│   │   │       │       └── keyboard_parser/ # JSON layout loading & floris data models
│   │   │       ├── latin/                # IME Lifecycle, input logic, dictionaries, suggestions
│   │   │       │   ├── ai/               # AI text assistant & prompt rewriting
│   │   │       │   ├── common/           # Colors, constants, lifecycle observers
│   │   │       │   ├── dictionary/       # Word dictionaries (User, Contacts, Suggest)
│   │   │       │   ├── inputlogic/       # Transactional text manipulation & auto-correct
│   │   │       │   ├── settings/         # Runtime settings caches and preferences data
│   │   │       │   ├── suggestions/      # Suggestion strip view & candidate models
│   │   │       │   ├── voice/            # Voice input recorder & speech transcription
│   │   │       │   └── utils/            # String, toolbar, clipboard, locale helpers
│   │   │       └── settings/             # Jetpack Compose Settings UI & screens
│   │   ├── jni/                          # C++ LatinIME engine (Trie, N-gram, Proximity)
│   │   └── res/                          # Android drawables, colors, styles, layouts, XMLs
│   └── build.gradle.kts                  # App module configuration & version codes
├── .agents/                              # AGY rules, skills, and memory
│   └── AGENTS.md                         # Project-specific AI agent operational rules
├── tools/                                # Utility scripts (update_outline.py, diacritics.py, etc.)
├── outline.md                            # Codebase architectural outline (This file, gitignored)
└── README.md                             # Project overview and documentation
```

---

## 3. Subsystem Breakdown & Key Class Map

### 3.1 IME Lifecycle & State Orchestration
* **`helium314.keyboard.latin.LatinIME`**: The central `InputMethodService`. Manages service lifecycle (`onCreate`, `onStartInputView`), dispatches hardware/software input, controls audio/haptics, coordinates with `RichInputConnection`, and handles window resizing.
* **`helium314.keyboard.keyboard.KeyboardSwitcher`**: Switches the active keyboard mode: alphabet, symbols, symbol shift, emoji palette, clipboard view, and one-handed layouts.
* **`helium314.keyboard.latin.RichInputConnection`**: Wrapper around Android's `InputConnection`. Manages cursor positions, batch edits, text deletion, selecting ranges, and text commits without crashing on buggy host apps.

### 3.2 Input Pipeline & Text Logic
* **`helium314.keyboard.latin.inputlogic.InputLogic`**: Central state machine for character insertion, composing words, backspace, auto-correction decisions, punctuation swaps, and double-space period insertion.
* **`helium314.keyboard.latin.WordComposer`**: Accumulates touch coordinates and characters for the currently active word being typed. Passes spatial touch history to the dictionary.
* **`helium314.keyboard.event.Event` / `EventDecoder`**: Decodes raw touch/key events into semantic keyboard actions (software keypress, hardware key, dead key combiners).

### 3.3 Keyboard UI & Canvas Drawing Pipeline
* **`helium314.keyboard.keyboard.MainKeyboardView`**: Top-level interactive keyboard custom `View`. Owns touch dispatching to `PointerTracker`, manages long-press popup panels, key previews, gesture trail rendering, and one-handed positioning.
* **`helium314.keyboard.keyboard.KeyboardView`**: The underlying canvas renderer. Draws key backgrounds (`onDrawKeyBackground`), custom key shapes (rectangles, rounded pills, hexagons), key labels, icons, subtext, and hint glyphs (`onDrawKeyTopVisuals`).
* **`helium314.keyboard.keyboard.Key`**: Model representing an individual key: absolute bounding coordinates (`x`, `y`, `width`, `height`), label, icon, background type, action flags, and hit boxes.
* **`helium314.keyboard.keyboard.PopupKeysKeyboardView`**: Mini keyboard canvas rendered inside a PopupWindow for long-press diacritics and secondary characters.

### 3.4 Touch Tracking & Hit Detection
* **`helium314.keyboard.keyboard.PointerTracker`**: High-performance multi-touch manager. Tracks pointers across frames, detects sliding input, long-press timeouts, swipe gestures (delete swipe, space swipe cursor move), and key repeat.
* **`helium314.keyboard.keyboard.KeyDetector`**: Base class mapping touch coordinates `(x, y)` to a `Key`.
  * **`ProximityKeyDetector`**: Standard AOSP detector applying bounding box proximity thresholds.
  * **`HexKeyDetector`**: Custom detector applying axial hexagonal hit math for honeycomb grids.

### 3.5 Layout Engine & Geometry Calculation
* **`helium314.keyboard.keyboard.internal.KeyboardBuilder`**: Takes parsed key rows and computes physical dimensions (`setAbsoluteDimensions`), gap distributions, row heights, and layout scaling. Contains custom branches like `determineHexAbsoluteValues()` for honeycomb grids.
* **`helium314.keyboard.keyboard.internal.keyboard_parser.KeyboardParser`**: High-level parser that stitches base layout rows together with functional rows (Shift, Delete, Space, Enter).
* **`helium314.keyboard.keyboard.internal.keyboard_parser.LayoutParser`**: Reads JSON layouts from `assets/layouts/` or user storage.
* **`helium314.keyboard.keyboard.internal.keyboard_parser.floris.*`**: FlorisBoard-compatible data definitions (`TextKeyData`, `KeyLabel`, `KeyCode`).
* **Active Built-In Layouts**: {layout_items_str}

### 3.6 Suggestions & Dictionary Engine
* **`helium314.keyboard.latin.suggestions.SuggestionStripView`**: The candidate bar above the keyboard displaying word completions, clipboard clips, or voice transcription status.
* **`helium314.keyboard.latin.Suggest`**: Queries dictionaries (main binary dictionary, user history dictionary, contacts) to produce ranked `SuggestedWords`.
* **`helium314.keyboard.latin.DictionaryFacilitatorImpl`**: Manages loading and caching of language dictionaries for active locales.
* **`app/src/main/jni/` (C++)**: Native implementation of the binary trie dictionary (`Dictionary`), N-gram language models, spatial proximity scoring (`ProximityInfo`), and gesture typing path recognition.

### 3.7 Voice & AI Assistant
* **`helium314.keyboard.latin.voice.VoiceInputManager`**: Handles audio recording, permission management, and communication with the transcription backend.
* **`com.leanbitlab.leantype.voice`**: Services connecting to Groq Whisper or local speech models.
* **`helium314.keyboard.latin.ai`**: LLM-assisted text rewriting (grammar correction, style change) via external or local AI APIs.

### 3.8 Settings & Preferences (Jetpack Compose)
* **`helium314.keyboard.settings.PreferencesSettingsActivity`**: Android activity hosting Compose settings.
* **Active Compose Screens**: {screen_items_str}
* **`helium314.keyboard.latin.settings.Settings` / `SettingsValues`**: Cached runtime snapshot of user preferences for zero-allocation access on the UI thread.

---

## 4. Quick Lookup: Where to Find What

| Developer Task / Bug Area | Primary Files & Classes to Inspect |
| :--- | :--- |
| **Key Rendering & Visuals** | `KeyboardView.kt`, `KeyDrawParams.kt`, `KeyVisualAttributes.kt` |
| **Touch Hit-Testing & Mis-taps** | `PointerTracker.kt`, `KeyDetector.kt`, `HexKeyDetector.kt` |
| **Grid Math, Scaling & Stagger** | `KeyboardBuilder.kt`, `KeyboardParams.kt` |
| **Layout Parsing & JSON Configs** | `KeyboardParser.kt`, `LayoutParser.kt`, `assets/layouts/` |
| **Functional Keys (Shift/Delete/Enter)** | `KeyLabel.kt`, `functional_keys.json`, `KeyboardParser.kt` |
| **Typing Latency, Text Insertion, Auto-correct** | `InputLogic.kt`, `WordComposer.kt`, `LatinIME.kt` |
| **Suggestion Bar & Candidate Scoring** | `SuggestionStripView.kt`, `Suggest.kt`, `DictionaryFacilitatorImpl.kt` |
| **Native Dictionary & Trie Lookup** | `com/android/inputmethod/latin/BinaryDictionary.java`, `app/src/main/jni/` |
| **Long-Press Diacritics & Popups** | `PopupKeysKeyboardView.kt`, `PopupKeysPanel.kt`, `TextKeyData.kt` |
| **Themes, Colors & Fonts** | `Colors.kt`, `KeyboardTheme.kt`, `AppearanceScreen.kt` |
| **Settings UI & Options** | `PreferencesSettingsActivity.kt`, `helium314/keyboard/settings/screens/` |
| **Voice Typing & AI Rewriter** | `VoiceInputManager.kt`, `com/leanbitlab/leantype/voice/`, `latin/ai/` |

---

## 5. Architectural Invariants for Agents

1. **Canvas Performance**: The main keyboard (`KeyboardView`) renders in under 16ms per frame. Never allocate large objects, run reflection, or perform file I/O inside `onDraw` or `onTouchEvent`.
2. **Hit Detection Separation**: `KeyDetector` must resolve hit keys purely via mathematical and bounding checks. Never couple hit testing with UI view states.
3. **Layout Normalization**: FlorisBoard relative widths within a row should sum to `1.0`. `KeyboardBuilder` maps these relative dimensions into absolute screen pixels taking paddings into account.
4. **Settings Thread Safety**: Preference reads during typing must use the cached immutable `SettingsValues` snapshot; avoid disk hits to `SharedPreferences` in active input loops.
"""
    return content


def update_outline():
    content = generate_outline_content()
    OUTLINE_FILE.write_text(content)
    print(f"Successfully updated {OUTLINE_FILE}")


if __name__ == "__main__":
    update_outline()
